import '../style/reset.scss';

export { default as Switch } from './switch/Switch.vue';
export { default as Button } from './button/Button.vue';
export { default as ButtonGroup } from './button/ButtonGroup.vue';
export { default as Dialog } from './dialog/Dialog.vue';
export { default as Tabs } from './tabs/Tabs.vue';
export { default as TabsPanel } from './tabs/TabsPanel.vue';
export { openDialog, alert, confirm, info } from './dialog/openDialog';
export { default as Checkbox } from './checkbox/Checkbox.vue';
export { default as Radio } from './radio/Radio.vue';
export { default as ControllCount } from './controll-count/ControllCount.vue';
export { default as Col } from './grid/Col.vue';
export { default as Row } from './grid/Row.vue';
export { default as Input } from './input/Input.vue';
export { default as Header } from './layout/Header.vue';
export { default as Footer } from './layout/Footer.vue';
export { default as Aside } from './layout/Aside.vue';
export { default as Layout } from './layout/Layout.vue';
export { default as Main } from './layout/Main.vue';
export { default as Pager } from './pager/Pager.vue';
